# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: pretty-format-json
        args: ['--no-sort-keys', '--autofix']
    -   id: no-commit-to-branch
        args: ['--pattern', '^(?!((afore|fondos|utileria)\/(ci|build|docs|feat|fix|perf|refactor|test)+-[a-z-]+-[0-9]+$)|(feature\/release-[0-9]+-[0-9]+-[0-9]$)).*']


#Comentado para dejar sólo black como filtro inicial.
#-   repo: https://github.com/sirosen/check-jsonschema
#    rev: 0.4.1
#    hooks:
#    -   id: check-github-workflows


-   repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.54.2
    hooks:
    -   id: cfn-python-lint
        exclude: |
            (?x)^(
                \.github.* |
                .pre-commit-config.yaml|
                .+\.json |
                .cz.yaml |
                .*openapi.yaml |
                .*asyncapi.yaml
            )$

-   repo: local
    hooks:
    -   id: illegalWords
        name: illegalWords
        entry: \-dev|335672086802|us-east-1|us-east-2
        language: pygrep
        types: [text]
        exclude: |
            (?x)^(
                .pre-commit-config.yaml|
                .cz.yaml |
                .+\.md |
                .cz.yaml |
                .*openapi.yaml |
                .*asyncapi.yaml |
                \.github.*
            )$

-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3


#Comentado para dejar sólo black como filtro inicial.
#-   repo: https://github.com/PyCQA/flake8
#    rev: 3.9.2
#    hooks:
#      - id: flake8
#        additional_dependencies: [flake8-docstrings, flake8-variables-names, pep8-naming]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.19.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
