#V1.0.0
name: manual_deploy_dev


on:

  workflow_dispatch:
    inputs:
      rama:
        description: Rama a desplegar
        required: true
        type: string
concurrency: develop

jobs:

  ############ PUSH A RAMA MAIN ##############
  # Si se hace push a la rama main:
  DevDeploy:
    #if: github.ref == 'refs/heads/main'
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      region: us-east-1
      ref: ${{github.event.inputs.rama}}
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}

  ReplicaDeploy:
    if: github.ref == 'refs/heads/main'
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      region: us-east-1
      ref: ${{ github.sha }}
      carpeta_sam: proyecto
      stack: proyecto
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}