#V1.0.0
name: manual_dynamo


on:
  
  workflow_dispatch:
    inputs:
      version:
        description: Versión a desplegar
        required: true
        type: string
      actualizacion_tablas:
        description: ¿Se actualizarán tablas?
        required: false
        type: boolean
      nuevas_tablas:
        description: ¿Se crearán tablas?
        required: false
        type: boolean
concurrency: develop

jobs:

  Hotfix:
    permissions: write-all
    #if: ${{github.event.inputs.ambiente == 'develop'}}
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_create_fix.yml@main
    with:
      ambiente: "develop"
      ref: ${{github.event.inputs.version}}
      fix: ${{github.event.inputs.version_fix}}
      region: us-east-1
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}

  DevDeploy:
    needs: Hotfix
    #if: github.ref == 'refs/heads/main'
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      region: us-east-1
      ref: fix/${{github.event.inputs.version_fix}}
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}
