#V1.0.0
name: manual_redeploy


on:
  
  workflow_dispatch:
    inputs:
      version:
        description: Número de release o pre-release a redesplegar.
        required: true
        type: string
      ambiente:
        description: Ambiente al cual se va a redesplegar.
        required: true
        type: choice
        options:
          - develop
          - preprod
          - production
  
jobs:

  RedeployDev:
    concurrency: develop
    if: ${{github.event.inputs.ambiente == 'develop'}}
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      ref: ${{github.event.inputs.version}}
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}

  RedeployPre:
    concurrency: preprod
    if: ${{github.event.inputs.ambiente == 'preprod'}}
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "preprod"
      ref: ${{github.event.inputs.version}}
    secrets:
      PRE_AWS_KEY_ID: ${{ secrets.VISOR_PRE_AWS_KEY_ID}}
      PRE_AWS_KEY_SECRET: ${{ secrets.VISOR_PRE_AWS_KEY_SECRET}}
      PRE_AWS_ACCOUNT_ID: ${{ secrets.VISOR_PRE_AWS_ACCOUNT_ID}}
      PRE_AWS_KMS: ${{ secrets.VISOR_PRE_AWS_KMS}}

  RedeployProd:
    concurrency: production
    if: ${{github.event.inputs.ambiente == 'production'}}
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "production"
      ref: ${{github.event.inputs.version}}
    secrets:
      PROD_AWS_KEY_ID: ${{ secrets.VISOR_PROD_AWS_KEY_ID}}
      PROD_AWS_KEY_SECRET: ${{ secrets.VISOR_PROD_AWS_KEY_SECRET}}
      PROD_AWS_ACCOUNT_ID: ${{ secrets.VISOR_PROD_AWS_ACCOUNT_ID}}
      PROD_AWS_KMS: ${{ secrets.VISOR_PROD_AWS_KMS}}
