#V1.0.0
name: manual_switch_r53

on:

  workflow_dispatch:
    inputs:
      ambiente:
        description: Cuidado. Switch para activar DR.
        required: true
jobs:
  SwitchRoute53:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ROUTE53_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.ROUTE53_AWS_SECRET }}
          aws-region: us-east-1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Haciendo Switch de dominios."
        run: |


          # Hacemos ejecutable.
          chmod u+x getroute.sh

          # Se ejecuta script en la misma terminal del contenedor del workflow.
          . getroute.sh
          
          # Se ejecuta script para hacer el switch de dominios.
          python switch.py -pd $PRIMARY_DOMAIN -pt $PRIMARY_TARGET -sd $FAILOVER_DOMAIN -st $FAILOVER_TARGET