#V1.0.0
name: manual_switch_r53

env:
  primary_domain: drtarget1.charlycloudy.com
  failover_domain: drtarget2.charlycloudy.com
  hosted_zone_id: ${{ secrets.ROUTE53_HOSTEDZONEID }}
  production_domain: produccion.charlycloudy.com
on:

  workflow_dispatch:

jobs:
  SwitchRoute53:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0    
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ROUTE53_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.ROUTE53_AWS_SECRET }}
          aws-region: us-east-1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: "Haciendo Switch de dominios."
        if: ${{ false }}
        run: |

          # Instalacion de boto3
          pip install boto3

          # Hacemos ejecutable.
          #chmod u+x getroute.sh

          # Se ejecuta script en la misma terminal del contenedor del workflow.
          #. getroute.sh -hz "${{env.hosted_zone_id}}" -pd "${{env.primary_domain}}" -fd "${{env.failover_domain}}"
          
          # Se ejecuta script para hacer el switch de dominios.
          python3 switch.py -hz "${{env.hosted_zone_id}}" -prd "${{env.production_domain}}" 

          # Se vuelve a ejecutar script para mostrar nuevos valores.
          . getroute.sh -hz "${{env.hosted_zone_id}}" -pd "${{env.primary_domain}}" -fd "${{env.failover_domain}}"