#V1.0.0
name: manual_pre-release


on:
  workflow_dispatch:
    inputs:
      version:
        description: Número de versión para el pre-release a crear. Seguir semantic versioning. Ejemplo 1.1.3
        required: true
        type: string
      hash:
        description: Commit en el cual se creará el pre-release. Ingresar los primeros 8 dígitos.
        type: string

concurrency: preprod

jobs:

  CreatePreRelease:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: "Validar número de versión"
        run: |
          echo "Version ${{github.event.inputs.version}}"
          [[ "${{github.event.inputs.version}}" =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$ ]] && echo "Correcto" || exit 1
          echo "Validando si ya existe un release"
          ! git ls-remote --exit-code --heads origin releases/${{github.event.inputs.version}}
          
          # En caso de que la longitud del hash sea menor a 8 marcar error.
          HASH=${{github.event.inputs.hash}}
          LONG=${#HASH}
          
          echo "El hash es:"
          echo $HASH

          # Validar longitud de hash de commit
          if [[ LONG != "" ]]; then echo "Validando longitud de hash...";
          elif [[ LONG -lt 8 ]]; then echo "La longitud es menor a 8..."; fi
          #echo "El Hash del commit no debe ser menor a 8 dígitos"; fi

          exit 1
      #- name: "Crear Tag en Hash de commit"
      #  run: 
        
      - name: Configurar Git
        run: |
          git config --global user.name 'Github'
          git config --global user.email 'workflow@noreply.github.com'
          git branch --show-current
      
      # Si el tag es nuevo lo crea
      # Si ya existe el tag, lo elimina del repositorio (local y remoto) y lo crea de nuevo en el ultimo commit de main
      - name: "Crear tag de pre-release"
        run: |
          #(git tag ${{github.event.inputs.version}}) || \
          #(git tag -d ${{github.event.inputs.version}} && git push --delete origin ${{github.event.inputs.version}} && git tag ${{github.event.inputs.version}})
          #git push origin ${{github.event.inputs.version}}
          git tag --force ${{github.event.inputs.version}}
          git push origin ${{github.event.inputs.version}} --force

      # Si el tag ya existía, al eliminarlo en el paso anterior se elimina el pre-release asociado
      # No es necesario un paso adicional para eliminar el pre-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.event.inputs.version}}
          prerelease: true
          body_path: ./CHANGELOG.md
        
  PreRelease:
    needs: CreatePreRelease
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "preprod"
      ref: "${{github.event.inputs.version}}"
      region: us-east-2
    secrets:
      PRE_AWS_KEY_ID: ${{ secrets.VISOR_PRE_AWS_KEY_ID}}
      PRE_AWS_KEY_SECRET: ${{ secrets.VISOR_PRE_AWS_KEY_SECRET}}
      PRE_AWS_ACCOUNT_ID: ${{ secrets.VISOR_PRE_AWS_ACCOUNT_ID}}
      PRE_AWS_KMS: ${{ secrets.VISOR_PRE_AWS_KMS}}
