#V1.0.0
name: manual_release


on:

  workflow_dispatch:
    inputs:
      version:
        description: Número de versión del pre-release a liberar.
        required: true
        type: string


jobs:

  Release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: "Validar número de versión"
        run: |
          echo "Version ${{github.event.inputs.version}}"
          [[ "${{github.event.inputs.version}}" =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*).*$ ]] && echo "Correcto" || exit 1
          echo "Validando si existe el pre-release"
          ! git tag ${{github.event.inputs.version}}
      
      - name: "Configurar Git"
        run: |
          git config --global user.name 'Github'
          git config --global user.email 'workflow@noreply.github.com'
          git branch --show-current
      
      - name: "Crear rama release"
        run: |
          git checkout -b releases/${{github.event.inputs.version}}
          git push origin releases/${{github.event.inputs.version}}

      # Se actualiza el release marcado como pre-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{github.event.inputs.version}}
          tag_name: ${{github.event.inputs.version}}
          generate_release_notes: false
          prerelease: false
          body_path: ./CHANGELOG.md