#V1.0.0
name: manual_hotfix


on:
  
  workflow_dispatch:
    inputs:
      version:
        description: Versión a la que se le hará hotfix
        required: true
        type: string
      version_fix:
        description: Versión que se estaría liberando para este fix. Ej. Si la versión a corregir es 3.0.1 esta versión sería 3.0.2
        required: true
        type: string

  
jobs:

  Hotfix:
    concurrency: develop
    #if: ${{github.event.inputs.ambiente == 'develop'}}
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_create_fix.yml@main
    with:
      ambiente: "develop"
      ref: ${{github.event.inputs.version}}
      fix: ${{github.event.inputs.version_fix}}
      region: us-east-1
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}

  DevDeploy:
    concurrency: develop
    #if: github.ref == 'refs/heads/main'
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      region: us-east-1
      ref: ${{github.event.inputs.version_fix}}
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}
