#V1.0.0
name: pre-release workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: Número de versión para el pre-release a crear. Seguir semantic versioning. Ejemplo 1.1.3
        required: true
        type: string

env:
  STACK_NAME: visor

jobs:
  PreRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: "Validar número de versión"
        run: |
          echo "Version ${{github.event.inputs.version}}-pre"
          [[ "${{github.event.inputs.version}}-pre" =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)-pre$ ]] && e
cho "Correcto" || exit 1
      - name: Configurar Git
        run: |
          git config --global user.name 'SIAGithub'
          git config --global user.email 'sia@noreply.github.com'
          git branch --show-current
      - name: "Crear rama pre-release"
        run: |
          git checkout pre-releases/${{github.event.inputs.version}}
          git tag ${{github.event.inputs.version}}-pre
          git push --tags -u origin pre-releases/${{github.event.inputs.version}}-pre
      - name: "Notificación de error"
        if: ${{ failure() }}
        run: |
          curl -H 'Content-Type: application/json' \
          --retry 4 \
          --retry-delay 1 \
          -d '{"text": "'"$PWD"' - '"$GITHUB_EVENT_NAME"' - ${{job.status}} - '"$GITHUB_REF"' - '"$GITHUB_BASE_REF"' "}' \
          https://mxspsolutions.webhook.office.com/webhookb2/a84b113f-9d27-4138-84ae-e3e4ab4830f2@ac5349df-152e-486f-9b39-fe3c4a25efe0/IncomingWebhook/e2f3db57ac59459a938f44c822548b89/10ed5eda-9b70-4598-858a-e5ae6599fa66