#V1.0.0
name: pre-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Número de versión para el pre-release a crear. Seguir semantic versioning. Ejemplo 1.1.3
        required: true
        type: string

jobs:
  CreatePreRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: "Validar número de versión"
        run: |
          echo "Version ${{github.event.inputs.version}}-pre"
          [[ "${{github.event.inputs.version}}-pre" =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)-pre$ ]] && echo "Correcto" || exit 1
      - name: Configurar Git
        run: |
          git config --global user.name 'Github'
          git config --global user.email 'workflow@noreply.github.com'
          git branch --show-current
      - name: "Crear tag de pre-release"
        run: |
          # Si el tag es nuevo lo crea
          # Si ya existe el tag, lo elimina del repositorio (local y remoto) y lo crea de nuevo en el ultimo commit de main
          (git tag ${{github.event.inputs.version}}-pre) || \
          (git tag -d ${{github.event.inputs.version}}-pre && git push --delete origin ${{github.event.inputs.version}}-pre && git tag ${{github.event.inputs.version}}-pre)
          git push origin ${{github.event.inputs.version}}-pre
      - name: "Notificación de error"
        if: ${{ failure() }}
        run: |
          curl -H 'Content-Type: application/json' \
          --retry 4 \
          --retry-delay 1 \
          -d '{"text": "'"$PWD"' - '"$GITHUB_EVENT_NAME"' - ${{job.status}} - '"$GITHUB_REF"' - '"$GITHUB_BASE_REF"' "}' \
          https://mxspsolutions.webhook.office.com/webhookb2/a84b113f-9d27-4138-84ae-e3e4ab4830f2@ac5349df-152e-486f-9b39-fe3c4a25efe0/IncomingWebhook/e2f3db57ac59459a938f44c822548b89/10ed5eda-9b70-4598-858a-e5ae6599fa66
  PreRelease:
    needs: CreatePreRelease
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/deploy-workflow.yml@main
    with:
      version: "${{github.event.inputs.version}}-pre"
      ambiente: "preprod"
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_REGION: ${{ secrets.VISOR_DEV_AWS_REGION}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}
      PRE_AWS_KEY_ID: ${{ secrets.VISOR_PRE_AWS_KEY_ID}}
      PRE_AWS_KEY_SECRET: ${{ secrets.VISOR_PRE_AWS_KEY_SECRET}}
      PRE_AWS_ACCOUNT_ID: ${{ secrets.VISOR_PRE_AWS_ACCOUNT_ID}}
      PRE_AWS_REGION: ${{ secrets.VISOR_PRE_AWS_REGION}}
      PRE_AWS_KMS: ${{ secrets.VISOR_PRE_AWS_KMS}}
      PROD_AWS_KEY_ID: ${{ secrets.VISOR_PROD_AWS_KEY_ID}}
      PROD_AWS_KEY_SECRET: ${{ secrets.VISOR_PROD_AWS_KEY_SECRET}}
      PROD_AWS_ACCOUNT_ID: ${{ secrets.VISOR_PROD_AWS_ACCOUNT_ID}}
      PROD_AWS_REGION: ${{ secrets.VISOR_PROD_AWS_REGION}}
      PROD_AWS_KMS: ${{ secrets.VISOR_PROD_AWS_KMS}}