#V1.0.0
name: push-manual_main


on:

  push:
    branches:
      - main
    paths:
      - '!**/.github/workflows/*.yml'  
      - '!**/.github/workflows/*.yaml' 

  workflow_dispatch:

  
jobs:

  ############ PUSH A RAMA MAIN ##############
  # Si se hace push a la rama main:
  DevDeploy:
    uses: test-org-123fdfsd/test-sam-cicd/.github/workflows/reusable_deploy.yml@main
    with:
      ambiente: "develop"
      ref: ${{ github.sha }}
    secrets:
      DEV_AWS_KEY_ID: ${{ secrets.VISOR_DEV_AWS_KEY_ID}}
      DEV_AWS_KEY_SECRET: ${{ secrets.VISOR_DEV_AWS_KEY_SECRET}}
      DEV_AWS_ACCOUNT_ID: ${{ secrets.VISOR_DEV_AWS_ACCOUNT_ID}}
      DEV_AWS_REGION: ${{ secrets.VISOR_DEV_AWS_REGION}}
      DEV_AWS_KMS: ${{ secrets.VISOR_DEV_AWS_KMS}}